# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\"\x07\n\x05\x45mpty\"3\n\x0c\x45mbedOptions\x12\r\n\x05model\x18\x01 \x01(\t\x12\x14\n\x0cmaxSeqLength\x18\x02 \x01(\x03\">\n\x0c\x45mbedRequest\x12\x11\n\tsentences\x18\x01 \x03(\t\x12\x1b\n\x13normalizeEmbeddings\x18\x02 \x01(\x08\"\x1b\n\nFloatArray\x12\r\n\x05\x61rray\x18\x01 \x03(\x02\")\n\nEmbeddings\x12\x1b\n\x06tensor\x18\x01 \x03(\x0b\x32\x0b.FloatArray2V\n\x0b\x45mbedServer\x12\"\n\tConfigure\x12\r.EmbedOptions\x1a\x06.Empty\x12#\n\x05\x45mbed\x12\r.EmbedRequest\x1a\x0b.EmbeddingsB\x1bZ\x19\x65mbed_server/embed_serverb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031embed_server/embed_server'
  _globals['_EMPTY']._serialized_start=13
  _globals['_EMPTY']._serialized_end=20
  _globals['_EMBEDOPTIONS']._serialized_start=22
  _globals['_EMBEDOPTIONS']._serialized_end=73
  _globals['_EMBEDREQUEST']._serialized_start=75
  _globals['_EMBEDREQUEST']._serialized_end=137
  _globals['_FLOATARRAY']._serialized_start=139
  _globals['_FLOATARRAY']._serialized_end=166
  _globals['_EMBEDDINGS']._serialized_start=168
  _globals['_EMBEDDINGS']._serialized_end=209
  _globals['_EMBEDSERVER']._serialized_start=211
  _globals['_EMBEDSERVER']._serialized_end=297
# @@protoc_insertion_point(module_scope)
