# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import embed_server.pb.api_pb2 as api__pb2


class EmbedServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Configure = channel.unary_unary(
                '/EmbedServer/Configure',
                request_serializer=api__pb2.EmbedOptions.SerializeToString,
                response_deserializer=api__pb2.Empty.FromString,
                )
        self.Embed = channel.unary_unary(
                '/EmbedServer/Embed',
                request_serializer=api__pb2.EmbedRequest.SerializeToString,
                response_deserializer=api__pb2.Embeddings.FromString,
                )


class EmbedServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Configure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbedServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=api__pb2.EmbedOptions.FromString,
                    response_serializer=api__pb2.Empty.SerializeToString,
            ),
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=api__pb2.EmbedRequest.FromString,
                    response_serializer=api__pb2.Embeddings.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EmbedServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EmbedServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EmbedServer/Configure',
            api__pb2.EmbedOptions.SerializeToString,
            api__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EmbedServer/Embed',
            api__pb2.EmbedRequest.SerializeToString,
            api__pb2.Embeddings.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
